version: "3.7"

services:
    api:
        build:
            context: ./back
        restart: always
        container_name: api
        ports:
            - "80:80"
        depends_on: 
            - api_database
        links: 
            - api_database
        env_file:
            - .env
    api_database:
        image: mysql:5.7.27
        restart: always
        command: '--explicit_defaults_for_timestamp'
        container_name: api_database
        ports:
            - "3306:3306"
        volumes:
            - ./database/data:/var/lib/mysql
            - ./database:/src/database
        env_file:
            - .env